### ISSUE TITLE
WIP: Make example with a nested condition

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/example-yarrrml-rules#2]
TODO: I still need to test this

```yaml
myMapping:
    sources:
      - ["data.csv~csv"]
    s: http://example.com#$(ID)
    po:
      - p: ex:relation
        o:
          - mapping: myOtherMapping # Just and example
            condition:
              function: grel:boolean_and
              parameters:
                - parameter: grel:param_rep_b
                  value:
                    function: equal
                      parameters:
                        - [str1, "$(myId)"]
                        - [str2, "$(myOtherId)"]
                - parameter: grel:param_rep_b
                  value:
                    function: equal
                      parameters:
                        - [str1, "$(myName)"]
                        - [str2, "$(myOtherName)"]
```
