### ISSUE TITLE
Unexpected characters error with XPath predicates

### ISSUE THREAD

**Issue by rwalpole** [RMLio/example-yarrrml-rules#6]
I have an `example.xml` file like this:
```
<people>
    <person id="I100194341916">
        <name>
            <nameForm>
                <part type="Given" value="Robert"/>
                <part type="Surname" value="Walpole"/>
            </nameForm>
        </name>
    </person>
</people>
```
and a YARRRML file like this:
```
prefixes:
  ex: http://example.org/
mappings:
  people:
    sources:
      - ['example.xml~xpath','/people/person']
    s: ex:person.$(@id)
    po:
      - [a, foaf:Person]
      - [foaf:givenName, $(name/nameForm/part[@type='Given']/@value)] 
```
When I try to parse the YARRRML I get an error:
```
line 8: Unexpected characters near "/@value)]".
```
However if I remove the XPath predicate `[@type='Given']` from the YARRRML and then modify the generated RML to re-add the predicate as follows:
```
:om_001 a rr:ObjectMap;
    rml:reference "name/nameForm/part[@type='Given']/@value";
    rr:termType rr:Literal.
```
Then the mapping works as expected.

Any thoughts on this please?

**Comment by bjdmeest** [comment]
I would expect that the `]` is confusing the YAML parsing step. Could you try by quoting the object value in YARRRML, like below?

```yaml
prefixes:
  ex: http://example.org/
mappings:
  people:
    sources:
      - ['example.xml~xpath','/people/person']
    s: ex:person.$(@id)
    po:
      - [a, foaf:Person]
      - [foaf:givenName, "$(name/nameForm/part[@type='Given']/@value)"] 
```
